title: Nick Manfredi
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0.9498208
  lightness: 0.9175627
  brandColors:
    - '#1689FC'
    - '#AC6503'
    - '#FF904D'
    - '#FAFFFF'
    - '#78759B'
  rhythmicContrast: 0.8691756
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Nick Manfredi
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5716846
layout_spectrum: 0.8351254
